name: profiling
version: 0.4.0
date: 19/01/2016
description: Line by line profiling and code coverage for GAP

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.6"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.4.4"
      url: "http://gap-system.github.io/io/"

www: http://gap-packages.github.io/profiling/
readme: http://gap-packages.github.io/profiling/README
packageinfo: http://gap-packages.github.io/profiling/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/profiling/releases/download/v0.4.0/profiling-0.4.0.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
