name: profiling
version: "2.5.4"
license: "MIT AND CDDL-1.0"
date: 2023-06-29
description: |
    Line by line profiling and code coverage for GAP

authors:
    - name: Christopher Jefferson
      url: https://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: https://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.10"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.4.4"
      url: "https://gap-packages.github.io/io"

www: https://gap-packages.github.io/profiling/
readme: README.md
packageinfo: https://gap-packages.github.io/profiling/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/profiling/releases/download/v2.5.4/profiling-2.5.4.tar.gz

abstract: |

status: deposited
doc-html: doc/chap0_mj.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Jef23</span>]   <b class='BibAuthor'>Jefferson, C.</b>,
     <i class='BibTitle'>profiling, Line by line profiling and code coverage for GAP,
             Version 2.5.4</i>
     (<span class='BibYear'>2023</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/profiling/">https://gap-packages.github.io/profiling/</a></span>.
    </p>
    

bibtex: |
    @misc{ profiling2.5.4,
      author =           {Jefferson, C.},
      title =            {{profiling},  Line by line profiling and code coverage
                          for GAP, {V}ersion 2.5.4},
      month =            {Jun},
      year =             {2023},
      note =             {GAP package},
      howpublished =     {\href      {https://gap-packages.github.io/profiling/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{profiling/}}},
      printedkey =       {Jef23}
    }

