name: profiling
version: 1.2.0
date: 11/01/2017
description: Line by line profiling and code coverage for GAP

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/

GAP: ">= 4.8"

needed-pkgs:
    - name: "GAPDoc"
      version: ">= 1.5"
      url: "http://www.math.rwth-aachen.de/~Frank.Luebeck/GAPDoc"
    - name: "IO"
      version: ">= 4.4.4"
      url: "https://gap-packages.github.io/io"

www: http://gap-packages.github.io/profiling/
readme: http://gap-packages.github.io/profiling/README
packageinfo: http://gap-packages.github.io/profiling/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/profiling/releases/download/v1.2.0/profiling-1.2.0.tar.gz

abstract: 

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
