name: CI

# Trigger the workflow on push or pull request
on:
  - push
  - pull_request

jobs:
  # The CI test job
  test:
    name: ${{ matrix.gap-branch }} ${{ matrix.ABI }}
    runs-on: ubuntu-latest
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    strategy:
      fail-fast: false
      matrix:
        gap-branch:
          - master
          - stable-4.11
          - stable-4.10
        ABI: ['']
        include:
          - gap-branch: master
            ABI: 32

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_BUILD: 'io' # exclude profiling, i.e., *this* package
          GAPBRANCH: ${{ matrix.gap-branch }}
          ABI: ${{ matrix.ABI }}
      - uses: gap-actions/build-pkg@v1
      - uses: gap-actions/run-pkg-tests@v2
        with:
          NO_COVERAGE: 'yes'
      - name: "Generate source coverage reports by running gcov"
        run: find . -type f -name '*.gcno' -exec gcov -pb {} +
      - uses: codecov/codecov-action@v2

  # The Cygwin job
  test-cygwin:
    name: 'cygwin64 - GAP master'
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}
    runs-on: windows-2019
    env:
      CHERE_INVOKING: 1
    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-cygwin@v1
      - uses: gap-actions/setup-gap@cygwin-v2
        with:
          GAP_PKGS_TO_BUILD: 'io'
      - uses: gap-actions/build-pkg@cygwin-v1
      # HACK: This test fails in GitHub Actions Cygwin
      - name: "HACK: Remove failing test files"
        run: rm tst/tstall/profilefile.tst
        shell: bash
      - uses: gap-actions/run-pkg-tests@cygwin-v2
        with:
          NO_COVERAGE: 'yes'
      - name: "Generate source coverage reports by running gcov"
        run: find . -type f -name '*.gcno' -exec gcov -pb {} +
        shell: bash
      - uses: codecov/codecov-action@v2
      - name: "Setup tmate session"
        uses: mxschmitt/action-tmate@v3
        if: ${{ failure() }}
        timeout-minutes: 15

  # The documentation job
  manual:
    name: Build manuals
    runs-on: ubuntu-latest
    # Don't run this twice on PRs for branches pushed to the same repository
    if: ${{ !(github.event_name == 'pull_request' && github.event.pull_request.head.repo.full_name == github.repository) }}

    steps:
      - uses: actions/checkout@v2
      - uses: gap-actions/setup-gap@v2
        with:
          GAP_PKGS_TO_BUILD: "io" # exclude profiling, i.e., *this* package
      - uses: gap-actions/build-pkg-docs@v1
        with:
          use-latex: 'true'
      - name: 'Upload documentation'
        uses: actions/upload-artifact@v2
        with:
          name: manual
          path: ./doc/manual.pdf
